num1=float(input("Enter 1st number: "))
num2=float(input("Enter 2nd number: "))
num3=float(input("Enter 3rd number: "))
print("Greatest number:", max(num1,num2,num3))
print("Smallest number:", min(num1,num2,num3))
